module cutit.cutit {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires com.jfoenix;
    requires java.datatransfer;
    requires java.desktop;
    requires java.sql;
    requires mysql.connector.java;
    requires javafx.web;
    requires com.dlsc.gmapsfx;


    exports cutit.facade;
    opens cutit.facade to javafx.fxml;
    exports cutit.controller.topbarviewcontrollers;
    opens cutit.controller.topbarviewcontrollers to javafx.fxml;
    exports cutit.decorator.decorator1.concrete_view_component;
    opens cutit.decorator.decorator1.concrete_view_component to javafx.fxml;
    exports cutit.bean;
    opens cutit.bean to javafx.fxml;
    exports cutit.controller.bookappointment;
    opens cutit.controller.bookappointment to javafx.fxml;
    exports cutit.controller.getlocationdirections;
    opens cutit.controller.getlocationdirections to javafx.fxml;
    exports cutit.controller.managepromotions;
    opens cutit.controller.managepromotions to javafx.fxml;
    exports cutit.controller.manageshoppage;
    opens cutit.controller.manageshoppage to javafx.fxml;
    exports cutit.controller.deletebookedappointments;
    opens cutit.controller.deletebookedappointments to javafx.fxml;
    exports cutit.controller.manageservices;
    opens cutit.controller.manageservices to javafx.fxml;
    exports cutit.controller.payonline;
    opens cutit.controller.payonline to javafx.fxml;
    exports cutit.controller.login;
    opens cutit.controller.login to javafx.fxml;
    exports cutit.bean.interfaces;
    opens cutit.bean.interfaces to javafx.fxml;
    exports cutit.pepper;
    opens cutit.pepper to javafx.fxml;
    exports cutit.controller.leftbarviewcontrollers;
    opens cutit.controller.leftbarviewcontrollers to javafx.fxml;
    exports cutit.decorator.decorator2.concrete_view_component2;
    opens cutit.decorator.decorator2.concrete_view_component2 to javafx.fxml;
    exports cutit.utils;
    exports cutit.model;
    exports cutit.decorator.decorator1;
    opens cutit.decorator.decorator1 to javafx.fxml;
    exports cutit.decorator.decorator2;
    opens cutit.decorator.decorator2 to javafx.fxml;
}